"El usuario introduce una fn genérica"
"Se emplean las restricciones para restringir puntos o rangos"
"se conforma un dominio"
"Se le solicita una intervalo de búsqueda de raíces"
"En caso de optar por no introducir uno, se realiza una búsqueda simétrica exponencial"
"Se aplica Bolzano"
"Se aplica la UI"
